### ISSUE TITLE
How to use Navicat to connect database by program 

### ISSUE THREAD

**Issue by cmzdandan** [DoubleLabyrinth/how-does-navicat-encrypt-password#5]
Even we know how the navicat to encrypt password, but how can we start navicat to connect database by code ?

**Comment by cmbsolutions** [comment]
Isn't that a bit out of scope? 

Anyway, you want to automate navicat? basicly, open navicat, open specific database and then let the user take over? why not give the user a shortcut to navicat and let him open the database...

If you want to get data from the database programmatically there are far better, faster ways to do that.

**Comment by cmzdandan** [comment]
Thanks for your reply.
Business needs are like this, users click a button which on the web page, then the local program start the navicat. The ip, port, username,password and so on infomation from the web, my local program receive the params and decode it, then deal with it, so that the navicat can be started and connected to the specified database.
In short, what I need to do is replace the user to fill in the base infomation for connect to database.
Now, my the train of thought is:
1. encode the password which I get from the param.(But I don't know how to encode it, you give the python code, I just use java and C#)
2. write the processed password to the Windows Registry.
3. start the navicat, and connect to database.
what the user did is click the button then the connection done by the program.


Thanks for your discusstion with me.
