### ISSUE TITLE
java or C# how to use blowfish like navicat does

### ISSUE THREAD

**Issue by cmzdandan** [DoubleLabyrinth/how-does-navicat-encrypt-password#6]
the example of python and cpp is very nice!
Can you give the Java or C# version code ?
Thanks!

**Comment by cmbsolutions** [comment]
hi, there is a dotnet folder with vb.net code. you can convert that online to C# (search telerik)

**Comment by DoubleLabyrinth** [comment]
I've add csharp implement for NavicatCrypto. You can see it in `csharp` folder.

**Comment by DoubleLabyrinth** [comment]
java implementation has been updated. You can see it in `java/NavicatCrypto` folder

**Comment by cmzdandan** [comment]
Thank you very very much!
You helped me a lot.
